version: "3.8"

services:
  openpose-ml:
    build: .
    container_name: openpose-thesis
    volumes:
      - .:/workspace  # Mount project directory for live coding
    stdin_open: true
    tty: true
    ports:
      - "8888:8888"  # For JupyterLab access